name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout this repo
        uses: actions/checkout@v2
        with:
          path: noisy

      - name: checkout logue-sdk
        uses: actions/checkout@v2
        with:
          repository: korginc/logue-sdk
          path: logue-sdk
          
      - name: install tooling
        run: sudo apt-get install gcc-arm-none-eabi
      
      - name: make
        run: |
          cd noisy
          make
          
      - name: publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: noisy.prlgunit
          path: noisy/noisy.prlgunit
