name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout this repo
        uses: actions/checkout@v2
        with:
          path: noisy

      - name: checkout logue-sdk
        uses: actions/checkout@v2
        with:
          repository: h2g2guy/logue-sdk
          path: logue-sdk
          submodules: recursive
          
      - name: cache tooling installation
        id: cache
        uses: actions/cache@v2
        with:
          path: logue-sdk/tools/gcc/gcc-arm-none-eabi-9-2020-q2-update
          key: gcc-${{ runner.os }}-${{ hashFiles('logue-sdk/tools/gcc/get-gcc-linux.sh') }}

      - name: install tooling
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pushd logue-sdk/tools/gcc
          ./get_gcc_linux.sh -s
          popd
      
      - name: make
        run: |
          cd noisy
          make
          
      - name: publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: noisy.prlgunit
          path: noisy/noisy.prlgunit
